mise à jour pour test deploy

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -44,7 +44,7 @@ jobs:
             echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
             docker push $DOCKERHUB_USERNAME/my-app:latest
 
-  deploy:
+ deploy:
     machine:
       resource_class: large  # Classe de ressources définie ici
     steps:
@@ -53,10 +53,14 @@ jobs:
       - run:
           name: Deploy to Render
           command: |
-            curl -X POST $HOOK_RENDER \
-            -H 'Authorization: Bearer $RENDER_API_KEY' \
-            -H 'Content-Type: application/json' \
-            -d '{"image": "docker.io/$DOCKERHUB_USERNAME/my-app:latest", "clearCache": false}'
+            if [ -z "$HOOK_RENDER" ]; then
+              echo "Error: HOOK_RENDER is not set"
+              exit 1
+            fi
+            curl -X POST "$HOOK_RENDER" \
+            -H "Authorization: Bearer $RENDER_API_KEY" \
+            -H "Content-Type: application/json" \
+            -d "{\"image\": \"docker.io/$DOCKERHUB_USERNAME/my-app:latest\", \"clearCache\": false}"
 
 workflows:
   build-and-deploy-workflow:
